/**
 * supabase.ts
 * Central data layer for Walkthrough AI.
 * Exports the Supabase client, all type definitions, and the
 * propertiesService object that every component uses to read/write data.
 */

import { createClient } from '@supabase/supabase-js';

// ─── Client setup ────────────────────────────────────────────────────────────

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error(
    'Missing Supabase environment variables. ' +
    'Make sure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set in your .env file.'
  );
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// ─── Types ───────────────────────────────────────────────────────────────────

/** Current processing status of a property record. */
export type PropertyStatus = 'recording' | 'processing' | 'completed' | 'error';

/**
 * Stages of the walkthrough workflow in order:
 *   walkthrough → outputs → followup → photos → generate
 */
export type WorkflowStage = 'walkthrough' | 'outputs' | 'followup' | 'photos' | 'generate';

/** All document types the AI can generate from a walkthrough. */
export type OutputType =
  | 'listing_pack'
  | 'inspection_notes'
  | 'client_summary'
  | 'offer_summary'
  | 'transaction_timeline'
  | 'disclosure_prep';

/** Human-readable label and description for each output type. */
export const OUTPUT_DEFINITIONS: Record<OutputType, { label: string; description: string }> = {
  listing_pack: {
    label: 'Property Listing Pack',
    description: 'Description, feature bullets, room breakdown, highlights & fact sheet',
  },
  inspection_notes: {
    label: 'Inspection Notes',
    description: 'Room-by-room observations, condition notes, maintenance flags, photo suggestions',
  },
  client_summary: {
    label: 'Client Summary Report',
    description: 'Buyer/seller preferences, priorities, budget constraints & next steps',
  },
  offer_summary: {
    label: 'Offer Summary Sheet',
    description: 'Offer amount, conditions, timelines, financing & contingencies (informational only)',
  },
  transaction_timeline: {
    label: 'Transaction Timeline',
    description: 'Milestones checklist: viewings, offers, inspections, closing & missing items',
  },
  disclosure_prep: {
    label: 'Disclosure Prep Assistant',
    description: 'Observed issues converted to prompts for seller confirmation (advisory only)',
  },
};

/** Outputs selected by default when starting a new walkthrough. */
export const DEFAULT_OUTPUTS: OutputType[] = ['listing_pack', 'client_summary'];

/**
 * A single agent-uploaded photo attached to one room of the walkthrough.
 * width/height are the actual pixel dimensions of the resized file that was
 * uploaded — recorded client-side so the server-side .docx builder can
 * scale the image into the Listing Pack without distorting it.
 */
export type FactSource =
  | 'observed'
  | 'seller_stated'
  | 'agent_stated'
  | 'user_confirmed'
  | 'external_document'
  | 'unverified'
  | 'unknown'
  | 'conflicting';

export interface RoomPhoto {
  /** Stable id so multiple images can coexist for one room. */
  id?: string;
  path: string;
  width: number;
  height: number;
}

export type RoomPhotoCollection = Record<string, RoomPhoto | RoomPhoto[]>;

export interface DocumentManifestEntry {
  status: 'generated' | 'failed' | 'omitted' | 'outdated';
  path?: string;
  data_version?: number;
  error?: string;
}

/** A follow-up question generated by the AI after transcription. */
export interface FollowUpQuestion {
  id: string;
  question: string;
  category: string;
  /** Dot-path into extraction_data this question targets, e.g. "fact_sheet.sqft". */
  field_path?: string;
}

/**
 * Fine-grained pipeline status used to show "Retrying..." instead of a
 * generic spinner or error while the edge function waits out a Gemini
 * rate limit.
 */
export type PipelineStatus =
  | 'idle' | 'extracting' | 'retrying_extraction'
  | 'generating' | 'retrying_generation' | 'done' | 'error';

/** Full property record as stored in Supabase. */
export interface Property {
  id: string;
  user_id: string;
  address: string;
  audio_storage_path: string | null;
  status: PropertyStatus;
  /** Legacy text fields kept for backward compatibility. */
  mls_description: string | null;
  feature_bullets: string | null;
  agent_remarks: string | null;
  crm_summary: string | null;
  error_message: string | null;
  /** Current position in the workflow. */
  workflow_stage?: WorkflowStage;
  /** Which output documents the user chose to generate. */
  selected_outputs?: string[];
  /** Generated output documents, one per OutputType. */
  listing_pack?: Record<string, unknown>;
  inspection_notes?: Record<string, unknown>;
  client_summary?: Record<string, unknown>;
  offer_summary?: Record<string, unknown>;
  transaction_timeline?: Record<string, unknown>;
  disclosure_prep?: Record<string, unknown>;
  /** AI-generated clarifying questions, stored after early Gemini call. */
  follow_up_questions?: FollowUpQuestion[];
  /** User-supplied answers to follow-up questions. */
  follow_up_answers?: Record<string, string>;
  /** Confidence score from extraction (0–1). Legacy — superseded by extraction_data per-field confidence. */
  extraction_confidence?: number;
  /** Raw structured data from AI extraction (legacy single-pass field). */
  structured_data?: Record<string, unknown>;
  /** Pass 1 structured extraction output with per-field confidence scores. */
  extraction_data?: Record<string, unknown> | null;
  /** Fine-grained pipeline status — used to show "Retrying..." during rate limits. */
  pipeline_status?: PipelineStatus;
  /** True once the walkthrough audio has been deleted from storage for privacy. */
  audio_deleted?: boolean;
  /** Storage paths for generated .docx files, keyed by output type.
   *  e.g. { listing_pack: "documents/{userId}/{propertyId}/listing-pack.docx" }
   *  The in-app viewer and download button both use these paths. */
  document_paths?: Record<string, string> | null;
  /** The exact brand colors/name used when this property's documents were
   *  generated — frozen at generation time so a document always looks the
   *  way it did that day, regardless of later Brand Kit changes. Null for
   *  properties generated before this existed (falls back to defaults). */
  document_brand?: { primary_hex: string; secondary_hex: string; brand_name: string } | null;
  /** Agent-uploaded room photos. New rows use arrays; old rows may still use one object. */
  room_photos?: RoomPhotoCollection | null;
  /** Version of the latest saved property facts. */
  property_data_version?: number;
  /** Property-data version used to create each current document. */
  document_data_versions?: Record<string, number> | null;
  /** Independent regeneration count per output type. */
  document_regeneration_counts?: Record<string, number> | null;
  /** Truthful per-output delivery status. */
  document_manifest?: Record<string, DocumentManifestEntry> | null;
  created_at: string;
}

/** Shape of the JSON returned by the /functions/v1/generate edge function. */
export interface GeneratedContent {
  listing_pack?: Record<string, unknown>;
  inspection_notes?: Record<string, unknown>;
  client_summary?: Record<string, unknown>;
  offer_summary?: Record<string, unknown>;
  transaction_timeline?: Record<string, unknown>;
  disclosure_prep?: Record<string, unknown>;
  follow_up_questions?: FollowUpQuestion[];
  /** True if the walkthrough audio was deleted from storage after this call. */
  _audio_deleted?: boolean;
  /** Present if documents were generated but the DB save failed. */
  _save_warning?: string;
}

/** Shape of the JSON returned by the /functions/v1/generate-followups edge function. */
export interface FollowUpResult {
  questions: FollowUpQuestion[];
}

/**
 * A user's Brand Kit — one per user. Colors are stored as keys into the
 * fixed 30-color palette (see src/utils/brandPalette.ts), never raw hex,
 * so the picker UI and the generated documents always agree on what each
 * color actually looks like.
 */
export interface BrandKit {
  id: string;
  user_id: string;
  brand_name: string;
  primary_color_key: string;
  secondary_color_key: string;
  created_at: string;
  updated_at: string;
}

// ─── Custom error class ───────────────────────────────────────────────────────

/**
 * GenerationError wraps failures from the edge function so callers can
 * inspect the HTTP status code alongside the human-readable message.
 */
export class GenerationError extends Error {
  status?: number;
  constructor(message: string, status?: number) {
    super(message);
    this.name = 'GenerationError';
    this.status = status;
  }
}

// ─── Properties service ───────────────────────────────────────────────────────

/**
 * propertiesService
 * All database and storage operations for property records.
 * Every method throws a descriptive error on failure — callers are
 * responsible for catching and displaying it to the user.
 */
export const propertiesService = {

  /**
   * Fetch all properties belonging to the current authenticated user,
   * ordered newest first.
   */
  async list(): Promise<Property[]> {
    const { data, error } = await supabase
      .from('properties')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) throw new Error(`Failed to load properties: ${error.message}`);
    return data ?? [];
  },

  /**
   * Fetch a single property by its ID.
   * Throws if the record doesn't exist or the user doesn't own it
   * (RLS will cause an empty result, treated as not-found).
   */
  async getById(id: string): Promise<Property> {
    const { data, error } = await supabase
      .from('properties')
      .select('*')
      .eq('id', id)
      .maybeSingle();

    if (error) throw new Error(`Failed to load property: ${error.message}`);
    if (!data) throw new Error('Property not found.');
    return data;
  },

  /**
   * Create a new property record.
   * Sets workflow_stage to 'walkthrough' — the correct starting stage.
   */
  async create(address: string, userId: string): Promise<Property> {
    const { data, error } = await supabase
      .from('properties')
      .insert({
        address,
        user_id: userId,
        workflow_stage: 'walkthrough', // flow always starts here
        status: 'recording',
      })
      .select()
      .single();

    if (error) throw new Error(`Failed to create property: ${error.message}`);
    return data;
  },

  /**
   * Partially update a property record by ID.
   * Returns the updated record.
   */
  async update(id: string, updates: Partial<Property>): Promise<Property> {
    const { data, error } = await supabase
      .from('properties')
      .update(updates)
      .eq('id', id)
      .select()
      .single();

    if (error) throw new Error(`Failed to update property: ${error.message}`);
    return data;
  },

  /** Save the canonical structured property record and advance its version. */
  async savePropertyFacts(
    id: string,
    extractionData: Record<string, unknown>,
    currentVersion = 1,
    documentManifest?: Record<string, DocumentManifestEntry>
  ): Promise<Property> {
    // Keep the facts and the affected-document markers in one update so a
    // refresh cannot show a saved fact without the corresponding status.
    return this.update(id, {
      extraction_data: extractionData,
      property_data_version: Math.max(1, currentVersion) + 1,
      ...(documentManifest ? { document_manifest: documentManifest } : {}),
    });
  },

  /**
   * Permanently delete a property record and its associated audio file.
   * Audio deletion is best-effort — a storage failure won't block the DB delete.
   */
  async remove(id: string): Promise<void> {
    // Fetch the audio path first so we can clean up storage
    const { data: prop } = await supabase
      .from('properties')
      .select('audio_storage_path')
      .eq('id', id)
      .maybeSingle();

    // Delete the DB record (cascades to nothing — aux tables were removed)
    const { error } = await supabase
      .from('properties')
      .delete()
      .eq('id', id);

    if (error) throw new Error(`Failed to delete property: ${error.message}`);

    // Best-effort: remove audio from storage
    if (prop?.audio_storage_path) {
      await supabase.storage
        .from('walkthrough-audio')
        .remove([prop.audio_storage_path])
        .catch(() => {
          // Non-fatal — orphaned audio files are acceptable
          console.warn('Could not delete audio file from storage:', prop.audio_storage_path);
        });
    }
  },

  /**
   * Upload an audio blob to the walkthrough-audio storage bucket.
   * Returns the storage path, which is saved on the property record.
   * Uses upsert so re-recording the same property replaces the old file.
   */
  async uploadAudio(propertyId: string, userId: string, blob: Blob): Promise<string> {
    // Pick the correct file extension from the blob MIME type
    const ext = blob.type.includes('mp4') || blob.type.includes('m4a')
      ? 'm4a'
      : blob.type.includes('ogg')
      ? 'ogg'
      : 'webm';

    const path = `${userId}/${propertyId}/walkthrough.${ext}`;

    const { error } = await supabase.storage
      .from('walkthrough-audio')
      .upload(path, blob, { contentType: blob.type, upsert: true });

    if (error) throw new Error(`Audio upload failed: ${error.message}`);
    return path;
  },

  /**
   * Resize an image file client-side before upload, using a canvas.
   * Keeps the original aspect ratio, scales down only (never up) so the
   * longest side is at most `maxDimension`, and re-encodes as JPEG to keep
   * upload size small. Returns the resized blob plus its final pixel
   * dimensions — the dimensions are stored in the DB alongside the photo so
   * the server-side .docx builder can scale it into the document correctly
   * without ever needing to decode the image itself.
   *
   * Throws a descriptive error if the file isn't a readable image — callers
   * show this directly to the user rather than failing silently.
   */
  async resizeImageForUpload(
    file: File,
    maxDimension = 1600,
    quality = 0.82
  ): Promise<{ blob: Blob; width: number; height: number }> {
    const objectUrl = URL.createObjectURL(file);
    try {
      const img = await new Promise<HTMLImageElement>((resolve, reject) => {
        const el = new Image();
        el.onload = () => resolve(el);
        el.onerror = () => reject(new Error('That file could not be read as an image. Please choose a photo (JPEG or PNG).'));
        el.src = objectUrl;
      });

      const scale = Math.min(1, maxDimension / Math.max(img.width, img.height));
      const width = Math.max(1, Math.round(img.width * scale));
      const height = Math.max(1, Math.round(img.height * scale));

      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext('2d');
      if (!ctx) throw new Error('Could not process this image on your device. Please try a different photo.');
      ctx.drawImage(img, 0, 0, width, height);

      const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/jpeg', quality));
      if (!blob) throw new Error('Could not process this image. Please try a different photo.');

      return { blob, width, height };
    } finally {
      URL.revokeObjectURL(objectUrl);
    }
  },

  /**
   * Upload a room photo to Storage and return its RoomPhoto record.
   * Uses the same `{userId}/{propertyId}/...` path scheme (and therefore
   * the same storage RLS policies) as the walkthrough audio upload — no
   * new storage policy was needed for this feature. `slotKey` is a stable,
   * filename-safe identifier for the room (see slugifyRoomName in
   * PhotosStage.tsx), used only for the storage path, not for display.
   */
  async uploadRoomPhoto(
    propertyId: string,
    userId: string,
    slotKey: string,
    file: File
  ): Promise<RoomPhoto> {
    const { blob, width, height } = await this.resizeImageForUpload(file);
    const id = typeof crypto !== 'undefined' && crypto.randomUUID
      ? crypto.randomUUID()
      : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
    const path = `${userId}/${propertyId}/photos/${slotKey}-${id}.jpg`;

    const { error } = await supabase.storage
      .from('walkthrough-audio')
      .upload(path, blob, { contentType: 'image/jpeg', upsert: true });

    if (error) throw new Error(`Photo upload failed: ${error.message}`);
    return { id, path, width, height };
  },

  /**
   * Remove a previously uploaded room photo from Storage. Storage failure
   * is non-fatal here — the caller always removes the DB reference to the
   * photo regardless, so a stray orphaned file in Storage never leaves the
   * property pointing at a photo the user believes they removed.
   */
  async removeRoomPhoto(path: string): Promise<void> {
    await supabase.storage
      .from('walkthrough-audio')
      .remove([path])
      .catch((err) => {
        console.warn('Could not delete room photo from storage (non-fatal):', path, err);
      });
  },

  /**
   * Call the generate edge function.
   *
   * Two-pass pipeline behaviour:
   *  - First call for a property (no extraction_data yet) runs Pass 1
   *    (extraction) and, if the audio is usable, immediately Pass 2 as
   *    well — so a single call can return documents.
   *  - Subsequent calls (extraction_data already exists) skip Pass 1 and
   *    run Pass 2 only, merging in followUpAnswers / manualData first.
   *
   * Returns the raw GeneratedContent so the caller can display it immediately
   * without an extra DB fetch — the edge function also writes to the DB.
   */
  async analyze(
    propertyId: string,
    audioStoragePath: string,
    selectedOutputs: OutputType[],
    /** Answers to FollowUpStage questions, keyed by question id. */
    followUpAnswers?: Record<string, string>,
    /** Manual data supplied via the SparseAudioView fill-in form, keyed by field name. */
    manualData?: Record<string, string>,
    /** Regenerate exactly one already-generated document from the saved property record. */
    regenerateOutput?: OutputType,
    /** QA-only pasted walkthrough text; mutually exclusive with audio input. */
    walkthroughText?: string,
  ): Promise<GeneratedContent> {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) throw new GenerationError('Not authenticated. Please sign in again.', 401);

    const response = await fetch(`${supabaseUrl}/functions/v1/generate`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${session.access_token}`,
        'apikey': supabaseAnonKey,
      },
      body: JSON.stringify({ propertyId, audioStoragePath, selectedOutputs, followUpAnswers, manualData, regenerateOutput, walkthroughText }),
    });

    const responseData = await response.json().catch(() => ({}));

    if (!response.ok) {
      const msg = (responseData as { error?: string })?.error
        || `Analysis failed (${response.status}). Please try again.`;
      throw new GenerationError(msg, response.status);
    }

    return responseData as GeneratedContent;
  },

  /**
   * Kick off the two-pass pipeline immediately after audio upload.
   *
   * This is fire-and-forget from WalkthroughStage/App.tsx: it calls the
   * `generate` edge function, which (since extraction_data doesn't exist
   * yet) runs Pass 1 (extraction) and then Pass 2 (a first draft of
   * documents), and triggers generate-followups in the background using
   * Pass 1's output. By the time the user reaches FollowUpStage,
   * follow_up_questions should already be saved on the property record.
   *
   * Returns the GeneratedContent (first-draft documents, or a sparse_audio
   * signal), or null if the call fails — failures are non-fatal because
   * GenerateStage will call analyze() again later and surface any error then.
   */
  async regenerateDocument(
    propertyId: string,
    output: OutputType
  ): Promise<GeneratedContent & Record<string, unknown>> {
    return await this.analyze(propertyId, '', [output], undefined, undefined, output) as GeneratedContent & Record<string, unknown>;
  },

  async startPipeline(
    propertyId: string,
    audioStoragePath: string,
    selectedOutputs: OutputType[],
    /** QA-only pasted walkthrough text. */
    walkthroughText?: string
  ): Promise<(GeneratedContent & Record<string, unknown>) | null> {
    try {
      return await this.analyze(propertyId, audioStoragePath, selectedOutputs, undefined, undefined, undefined, walkthroughText) as GeneratedContent & Record<string, unknown>;
    } catch (err) {
      console.warn('startPipeline (Pass 1) failed (non-fatal):', err);
      return null;
    }
  },
};

// ─── Brand Kit service ─────────────────────────────────────────────────────────

/**
 * brandKitService
 * All database operations for the current user's Brand Kit (one per user).
 * Every method throws a descriptive error on failure — callers are
 * responsible for catching and displaying it to the user.
 */
export const brandKitService = {
  /**
   * Fetch the current user's Brand Kit, or null if they haven't created
   * one yet (this is a normal, expected state — not an error).
   */
  async get(): Promise<BrandKit | null> {
    const { data, error } = await supabase
      .from('brand_kits')
      .select('*')
      .maybeSingle();

    if (error) throw new Error(`Failed to load your Brand Kit: ${error.message}`);
    return data;
  },

  /**
   * Create or update the current user's Brand Kit.
   * Uses upsert on user_id so this works whether or not a kit exists yet.
   */
  async save(
    userId: string,
    brandName: string,
    primaryColorKey: string,
    secondaryColorKey: string
  ): Promise<BrandKit> {
    const { data, error } = await supabase
      .from('brand_kits')
      .upsert(
        {
          user_id: userId,
          brand_name: brandName,
          primary_color_key: primaryColorKey,
          secondary_color_key: secondaryColorKey,
          updated_at: new Date().toISOString(),
        },
        { onConflict: 'user_id' }
      )
      .select()
      .single();

    if (error) throw new Error(`Failed to save your Brand Kit: ${error.message}`);
    return data;
  },
};

/**
 * Get a short-lived signed URL for a generated .docx file in Supabase Storage.
 * Used by the in-app viewer (mammoth) and the download button.
 * URLs expire after 1 hour — sufficient for a single session.
 */
export async function getDocumentSignedUrl(storagePath: string): Promise<string> {
  const { data, error } = await supabase.storage
    .from('walkthrough-audio')
    .createSignedUrl(storagePath, 3600); // 1 hour

  if (error || !data?.signedUrl) {
    throw new Error(`Could not get signed URL for ${storagePath}: ${error?.message ?? 'unknown error'}`);
  }
  return data.signedUrl;
}
