/**
 * supabase.ts
 * Central data layer for Walkthrough AI.
 * Exports the Supabase client, all type definitions, and the
 * propertiesService object that every component uses to read/write data.
 */

import { createClient } from '@supabase/supabase-js';

// ─── Client setup ────────────────────────────────────────────────────────────

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error(
    'Missing Supabase environment variables. ' +
    'Make sure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set in your .env file.'
  );
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// ─── Types ───────────────────────────────────────────────────────────────────

/** Current processing status of a property record. */
export type PropertyStatus = 'recording' | 'processing' | 'completed' | 'error';

/**
 * Stages of the walkthrough workflow in order:
 *   walkthrough → outputs → followup → photos → generate
 */
export type WorkflowStage = 'walkthrough' | 'outputs' | 'followup' | 'photos' | 'generate';

/** All document types the AI can generate from a walkthrough. */
export type OutputType =
  | 'listing_pack'
  | 'inspection_notes'
  | 'client_summary'
  | 'offer_summary'
  | 'transaction_timeline'
  | 'disclosure_prep';

/** Human-readable label and description for each output type. */
export const OUTPUT_DEFINITIONS: Record<OutputType, { label: string; description: string }> = {
  listing_pack: {
    label: 'Property Listing Pack',
    description: 'Description, feature bullets, room breakdown, highlights & fact sheet',
  },
  inspection_notes: {
    label: 'Inspection Notes',
    description: 'Room-by-room observations, condition notes, maintenance flags, photo suggestions',
  },
  client_summary: {
    label: 'Client Summary Report',
    description: 'Buyer/seller preferences, priorities, budget constraints & next steps',
  },
  offer_summary: {
    label: 'Offer Summary Sheet',
    description: 'Offer amount, conditions, timelines, financing & contingencies (informational only)',
  },
  transaction_timeline: {
    label: 'Transaction Timeline',
    description: 'Milestones checklist: viewings, offers, inspections, closing & missing items',
  },
  disclosure_prep: {
    label: 'Disclosure Prep Assistant',
    description: 'Observed issues converted to prompts for seller confirmation (advisory only)',
  },
};

/** Outputs selected by default when starting a new walkthrough. */
export const DEFAULT_OUTPUTS: OutputType[] = ['listing_pack', 'client_summary'];

/**
 * A single agent-uploaded photo attached to one room of the walkthrough.
 * width/height are the actual pixel dimensions of the resized file that was
 * uploaded — recorded client-side so the server-side .docx builder can
 * scale the image into the Listing Pack without distorting it.
 */
export type FactSource =
  | 'observed'
  | 'seller_stated'
  | 'agent_stated'
  | 'user_confirmed'
  | 'external_document'
  | 'unverified'
  | 'unknown'
  | 'conflicting';

export interface RoomPhoto {
  /** Stable id so multiple images can coexist for one room. */
  id?: string;
  path: string;
  width: number;
  height: number;
}

export type RoomPhotoCollection = Record<string, RoomPhoto | RoomPhoto[]>;

export interface DocumentManifestEntry {
  status: 'generated' | 'failed' | 'omitted' | 'outdated';
  path?: string;
  data_version?: number;
  error?: string;
}

/** A follow-up question generated by the AI after transcription. */
export interface FollowUpQuestion {
  id: string;
  question: string;
  category: string;
  /** Dot-path into extraction_data this question targets, e.g. "fact_sheet.sqft". */
  field_path?: string;
}

/**
 * Fine-grained pipeline status used to show "Retrying..." instead of a
 * generic spinner or error while the edge function waits out a Gemini
 * rate limit.
 */
export type PipelineStatus =
  | 'idle' | 'extracting' | 'retrying_extraction'
  | 'generating' | 'retrying_generation' | 'done' | 'error';

/** Full property record as stored in Supabase. */
export interface Property {
  id: string;
  user_id: string;
  address: string;
  audio_storage_path: string | null;
  status: PropertyStatus;
  /** Legacy text fields kept for backward compatibility. */
  mls_description: string | null;
  feature_bullets: string | null;
  agent_remarks: string | null;
  crm_summary: string | null;
  error_message: string | null;
  /** Current position in the workflow. */
  workflow_stage?: WorkflowStage;
  /** Which output documents the user chose to generate. */
  selected_outputs?: string[];
  /** Generated output documents, one per OutputType. */
  listing_pack?: Record<string, unknown>;
  inspection_notes?: Record<string, unknown>;
  client_summary?: Record<string, unknown>;
  offer_summary?: Record<string, unknown>;
  transaction_timeline?: Record<string, unknown>;
  disclosure_prep?: Record<string, unknown>;
  /** AI-generated clarifying questions, stored after early Gemini call. */
  follow_up_questions?: FollowUpQuestion[];
  /** User-supplied answers to follow-up questions. */
  follow_up_answers?: Record<string, string>;
  /** Confidence score from extraction (0–1). Legacy — superseded by extraction_data per-field confidence. */
  extraction_confidence?: number;
  /** Raw structured data from AI extraction (legacy single-pass field). */
  structured_data?: Record<string, unknown>;
  /** Pass 1 structured extraction output with per-field confidence scores. */
  extraction_data?: Record<string, unknown> | null;
  /** Fine-grained pipeline status — used to show "Retrying..." during rate limits. */
  pipeline_status?: PipelineStatus;
  /** True once the walkthrough audio has been deleted from storage for privacy. */
  audio_deleted?: boolean;
  /** Storage paths for generated .docx files, keyed by output type.
   *  e.g. { listing_pack: "documents/{userId}/{propertyId}/listing-pack.docx" }
   *  The in-app viewer and download button both use these paths. */
  document_paths?: Record<string, string> | null;
  /** The exact brand colors/name used when this property's documents were
   *  generated — frozen at generation time so a document always looks the
   *  way it did that day, regardless of later Brand Kit changes. Null for
   *  properties generated before this existed (falls back to defaults). */
  document_brand?: { primary_hex: string; secondary_hex: string; brand_name: string } | null;
  /** Agent-uploaded room photos. New rows use arrays; old rows may still use one object. */
  room_photos?: RoomPhotoCollection | null;
  /** Version of the latest saved property facts. */
  property_data_version?: number;
  /** Property-data version used to create each current document. */
  document_data_versions?: Record<string, number> | null;
  /** Independent regeneration count per output type. */
  document_regeneration_counts?: Record<string, number> | null;
  /** Truthful per-output delivery status. */
  document_manifest?: Record<string, DocumentManifestEntry> | null;
  created_at: string;
}

/** Shape of the JSON returned by the /functions/v1/generate edge function. */
export interface GeneratedContent {
  listing_pack?: Record<string, unknown>;
  inspection_notes?: Record<string, unknown>;
  client_summary?: Record<string, unknown>;
  offer_summary?: Record<string, unknown>;
  transaction_timeline?: Record<string, unknown>;
  disclosure_prep?: Record<string, unknown>;
  follow_up_questions?: FollowUpQuestion[];
  /** True if the walkthrough audio was deleted from storage after this call. */
  _audio_deleted?: boolean;
  /** Present if documents were generated but the DB save failed. */
  _save_warning?: string;
}

/** Shape of the JSON returned by the /functions/v1/generate-followups edge function. */
export interface FollowUpResult {
  questions: FollowUpQuestion[];
}

/**
 * A user's Brand Kit — one per user. Colors are stored as keys into the
 * fixed 30-color palette (see src/utils/brandPalette.ts), never raw hex,
 * so the picker UI and the generated documents always agree on what each
 * color actually looks like.
 */
export interface BrandKit {
  id: string;
  user_id: string;
  brand_name: string;
  primary_color_key: string;
  secondary_color_key: string;
  created_at: string;
  updated_at: string;
}

// ─── Custom error class ───────────────────────────────────────────────────────

/**
 * GenerationError wraps failures from the edge function so callers can
 * inspect the HTTP status code alongside the human-readable message.
 */
export class GenerationError extends Error {
  status?: number;
  constructor(message: string, status?: number) {
    super(message);
    this.name = 'GenerationError';
    this.status = status;
  }
}

// ─── Properties service ───────────────────────────────────────────────────────

/**
 * propertiesService
 * All database and storage operations for property records.
 * Every method throws a descriptive error on failure — callers are
 * responsible for catching and displaying it to the user.
 */
export const propertiesService = {

  /**
   * Fetch all properties belonging to the current authenticated user,
   * ordered newest first.
   */
  async list(): Promise<Property[]> {
    const { data, error } = await supabase
      .from('properties')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) throw new Error(`Failed to load properties: ${error.message}`);
    return data ?? [];
  },

  /**
   * Fetch a single property by its ID.
   * Throws if the record doesn't exist or the user doesn't own it
   * (RLS will cause an empty result, treated as not-found).
   */
  async getById(id: string): Promise<Property> {
    const { data, error } = await supabase
      .from('properties')
      .select('*')
      .eq('id', id)
      .maybeSingle();

    if (error) throw new Error(`Failed to load property: ${error.message}`);
    if (!data) throw new Error('Property not found.');
    return data;
  },

  /**
   * Create a new property record.
   * Sets workflow_stage to 'walkthrough' — the correct starting stage.
   */
  async create(address: string, userId: string): Promise<Property> {
    const { data, error } = await supabase
      .from('properties')
      .insert({
        address,
        user_id: userId,
        workflow_stage: 'walkthrough', // flow always starts here
        status: 'recording',
      })
      .select()
      .single();

    if (error) throw new Error(`Failed to create property: ${error.message}`);
    return data;
  },

  /**
   * Partially update a property record by ID.
   * Returns the updated record.
   */
  async update(id: string, updates: Partial<Property>): Promise<Property> {
    const { data, error } = await supabase
      .from('properties')
      .update(updates)
      .eq('id', id)
      .select()
      .single();

    if (error) throw new Error(`Failed to update property: ${error.message}`);
    return data;
  },

  /** Save the canonical structured property record and advance its version. */
  async savePropertyFacts(
    id: string,
    extractionData: Record<string, unknown>,
    currentVersion = 1,
    documentManifest?: Record<string, DocumentManifestEntry>
  ): Promise<Property> {
    // Keep the facts and the affected-document markers in one update so a
    // refresh cannot show a saved fact without the corresponding status.
    return this.update(id, {
      extraction_data: extractionData,
      property_data_version: Math.max(1, currentVersion) + 1,
      ...(documentManifest ? { document_manifest: documentManifest } : {}),
    });
  },

  /**
   * Permanently delete a property record and its associated audio file.
   * Audio deletion is best-effort — a storage failure won't block the DB delete.
   */
  async remove(id: string): Promise<void> {
    // Fetch the audio path first so we can clean up storage
    const { data: prop } = await supabase
      .from('properties')
      .select('audio_storage_path')
      .eq('id', id)
      .maybeSingle();

    // Delete the DB record (cascades to nothing — aux tables were removed)
    const { error } = await supabase
      .from('properties')
      .delete()
      .eq('id', id);

    if (error) throw new Error(`Failed to delete property: ${error.message}`);

    // Best-effort: remove audio from storage
    if (prop?.audio_storage_path) {
      await supabase.storage
        .from('walkthrough-audio')
        .remove([prop.audio_storage_path])
        .catch(() => {
          // Non-fatal — orphaned audio files are acceptable
          console.warn('Could not delete audio file from storage:', prop.audio_storage_path);
        });
    }
  },

  /**
   * Upload an audio blob to the walkthrough-audio storage bucket.
   * Returns the storage path, which is saved on the property record.
   * Uses upsert so re-recording the same property replaces the old file.
   */
  async uploadAudio(propertyId: string, userId: string, blob: Blob): Promise<string> {
    // Pick the correct file extension from the blob MIME type
    const ext = blob.type.includes('mp4') || blob.type.includes('m4a')
      ? 'm4a'
      : blob.type.includes('ogg')
      ? 'ogg'
      : 'webm';

    const path = `${userId}/${propertyId}/walkthrough.${ext}`;

    const { error } = await supabase.storage
      .from('walkthrough-audio')
      .upload(path, blob, { contentType: blob.type, upsert: true });

    if (error) throw new Error(`Audio upload failed: ${error.message}`);
    return path;
  },

  /**
   * Resize an image file client-side before upload, using a canvas.
   * Keeps the original aspect ratio, scales down only (never up) so the
   * longest side is at most `maxDimension`, and re-encodes as JPEG to keep
   * upload size small. Returns the resized blob plus its final pixel
   * dimensions — the dimensions are stored in the DB alongside the photo so
   * the server-side .docx builder can scale it into the document correctly
   * without ever needing to decode the image itself.
   *
   * Throws a descriptive error if the file isn't a readable image — callers
   * show this directly to the user rather than failing silently.
   */
  async resizeImageForUpload(
    file: File,
    maxDimension = 1600,
    quality = 0.82
  ): Promise<{ blob: Blob; width: number; height: number }> {
    const objectUrl = URL.createObjectURL(file);
    try {
      const img = await new Promise<HTMLImageElement>((resolve, reject) => {
        const el = new Image();
        el.onload = () => resolve(el);
        el.onerror = () => reject(new Error('That file could not be read as an image. Please choose a photo (JPEG or PNG).'));
        el.src = objectUrl;
      });

      const scale = Math.min(1, maxDimension / Math.max(img.width, img.height));
      const width = Math.max(1, Math.round(img.width * scale));
      const height = Math.max(1, Math.round(img.height * scale));

      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext('2d');
      if (!ctx) throw new Error('Could not process this image on your device. Please try a different photo.');
      ctx.drawImage(img, 0, 0, width, height);

      const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/jpeg', quality));
      if (!blob) throw new Error('Could not process this image. Please try a different photo.');

      return { blob, width, height };
    } finally {
      URL.revokeObjectURL(objectUrl);
    }
  },

  /**
   * Upload a room photo to Storage and return its RoomPhoto record.
   * Uses the same `{userId}/{propertyId}/...` path scheme (and therefore
   * the same storage RLS policies) as the walkthrough audio upload — no
   * new storage policy was needed for this feature. `slotKey` is a stable,
   * filename-safe identifier for the room (see slugifyRoomName in
   * PhotosStage.tsx), used only for the storage path, not for display.
   */
  async uploadRoomPhoto(
    propertyId: string,
    userId: string,
    slotKey: string,
    file: File
  ): Promise<RoomPhoto> {
    const { blob, width, height } = await this.resizeImageForUpload(file);
    const id = typeof crypto !== 'undefined' && crypto.randomUUID
      ? crypto.randomUUID()
      : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
    const path = `${userId}/${propertyId}/photos/${slotKey}-${id}.jpg`;

    const { error } = await supabase.storage
      .from('walkthrough-audio')
      .upload(path, blob, { contentType: 'image/jpeg', upsert: true });

    if (error) throw new Error(`Photo upload failed: ${error.message}`);
    return { id, path, width, height };
  },

  /**
   * Remove a previously uploaded room photo from Storage. Storage failure
   * is non-fatal here — the caller always removes the DB reference to the
   * photo regardless, so a stray orphaned file in Storage never leaves the
   * property pointing at a photo the user believes they removed.
   */
  async removeRoomPhoto(path: string): Promise<void> {
    await supabase.storage
      .from('walkthrough-audio')
      .remove([path])
      .catch((err) => {
        console.warn('Could not delete room photo from storage (non-fatal):', path, err);
      });
  },

  /**
   * Call the generate edge function.
   *
   * Two-pass pipeline behaviour:
   *  - First call for a property (no extraction_data yet) runs Pass 1
   *    (extraction) and, if the audio is usable, immediately Pass 2 as
   *    well — so a single call can return documents.
   *  - Subsequent calls (extraction_data already exists) skip Pass 1 and
   *    run Pass 2 only, merging in followUpAnswers / manualData first.
   *
   * Returns the raw GeneratedContent so the caller can display it immediately
   * without an extra DB fetch — the edge function also writes to the DB.
   */
  async analyze(
    propertyId: string,
    audioStoragePath: string,
    selectedOutputs: OutputType[],
    /** Answers to FollowUpStage questions, keyed by question id. */
    followUpAnswers?: Record<string, string>,
    /** Manual data supplied via the SparseAudioView fill-in form, keyed by field name. */
    manualData?: Record<string, string>,
    /** Regenerate exactly one already-generated document from the saved property record. */
    regenerateOutput?: OutputType,
    /** Testing-only pasted walkthrough text; mutually exclusive with audio input. */
    walkthroughText?: string,
  ): Promise<GeneratedContent> {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) throw new GenerationError('Not authenticated. Please sign in again.', 401);

    const response = await fetch(`${supabaseUrl}/functions/v1/generate`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${session.access_token}`,
        'apikey': supabaseAnonKey,
      },
      body: JSON.stringify({ propertyId, audioStoragePath, selectedOutputs, followUpAnswers, manualData, regenerateOutput, walkthroughText }),
    });

    const responseData = await response.json().catch(() => ({}));

    if (!response.ok) {
      const msg = (responseData as { error?: string })?.error
        || `Analysis failed (${response.status}). Please try again.`;
      throw new GenerationError(msg, response.status);
    }

    return responseData as GeneratedContent;
  },

  /**
   * Kick off the two-pass pipeline immediately after audio upload.
   *
   * This is fire-and-forget from WalkthroughStage/App.tsx: it calls the
   * `generate` edge function, which (since extraction_data doesn't exist
   * yet) runs Pass 1 (extraction) and then Pass 2 (a first draft of
   * documents), and triggers generate-followups in the background using
   * Pass 1's output. By the time the user reaches FollowUpStage,
   * follow_up_questions should already be saved on the property record.
   *
   * Returns the GeneratedContent (first-draft documents, or a sparse_audio
   * signal), or null if the call fails — failures are non-fatal because
   * GenerateStage will call analyze() again later and surface any error then.
   */
  async regenerateDocument(
    propertyId: string,
    output: OutputType
  ): Promise<GeneratedContent & Record<string, unknown>> {
    return await this.analyze(propertyId, '', [output], undefined, undefined, output) as GeneratedContent & Record<string, unknown>;
  },

  async startPipeline(
    propertyId: string,
    audioStoragePath: string,
    selectedOutputs: OutputType[],
    /** Testing-only pasted walkthrough text. */
    walkthroughText?: string,
  ): Promise<(GeneratedContent & Record<string, unknown>) | null> {
    try {
      return await this.analyze(propertyId, audioStoragePath, selectedOutputs, undefined, undefined, undefined, walkthroughText) as GeneratedContent & Record<string, unknown>;
    } catch (err) {
      console.warn('startPipeline (Pass 1) failed (non-fatal):', err);
      return null;
    }
  },
};

// ─── Brand Kit service ─────────────────────────────────────────────────────────

/**
 * brandKitService
 * All database operations for the current user's Brand Kit (one per user).
 * Every method throws a descriptive error on failure — callers are
 * responsible for catching and displaying it to the user.
 */
export const brandKitService = {
  /**
   * Fetch the current user's Brand Kit, or null if they haven't created
   * one yet (this is a normal, expected state — not an error).
   */
  async get(): Promise<BrandKit | null> {
    const { data, error } = await supabase
      .from('brand_kits')
      .select('*')
      .maybeSingle();

    if (error) throw new Error(`Failed to load your Brand Kit: ${error.message}`);
    return data;
  },

  /**
   * Create or update the current user's Brand Kit.
   * Uses upsert on user_id so this works whether or not a kit exists yet.
   */
  async save(
    userId: string,
    brandName: string,
    primaryColorKey: string,
    secondaryColorKey: string
  ): Promise<BrandKit> {
    const { data, error } = await supabase
      .from('brand_kits')
      .upsert(
        {
          user_id: userId,
          brand_name: brandName,
          primary_color_key: primaryColorKey,
          secondary_color_key: secondaryColorKey,
          updated_at: new Date().toISOString(),
        },
        { onConflict: 'user_id' }
      )
      .select()
      .single();

    if (error) throw new Error(`Failed to save your Brand Kit: ${error.message}`);
    return data;
  },
};

/**
 * Get a short-lived signed URL for a generated .docx file in Supabase Storage.
 * Used by the in-app viewer (mammoth) and the download button.
 * URLs expire after 1 hour — sufficient for a single session.
 */
export async function getDocumentSignedUrl(storagePath: string): Promise<string> {
  const { data, error } = await supabase.storage
    .from('walkthrough-audio')
    .createSignedUrl(storagePath, 3600); // 1 hour

  if (error || !data?.signedUrl) {
    throw new Error(`Could not get signed URL for ${storagePath}: ${error?.message ?? 'unknown error'}`);
  }
  return data.signedUrl;
}

// ─── V84 seller Home Launch Checklist ─────────────────────────────────────────

export type LaunchTaskCategory = 'fix' | 'prepare' | 'proof' | 'access';
export type LaunchTaskStatus = 'not_started' | 'in_progress' | 'submitted' | 'needs_help' | 'not_applicable' | 'reviewed';

export interface SellerContact { id: string; agent_id: string; name: string; email: string | null; role: 'seller' | 'buyer' | 'both'; }
export interface HomeLaunchPlan { id: string; agent_id: string; property_id: string; seller_contact_id: string | null; status: 'draft' | 'shared' | 'submitted' | 'under_review' | 'ready'; agent_intro: string | null; launch_target_date: string | null; created_at: string; updated_at: string; }
export interface HomeLaunchTask { id: string; plan_id: string; agent_id: string; category: LaunchTaskCategory; title: string; why_it_matters: string | null; mandatory: boolean; requires_upload: boolean; requires_review: boolean; due_date: string | null; display_order: number; seller_status: LaunchTaskStatus; seller_completion_date: string | null; seller_note: string | null; agent_review_status: 'pending' | 'approved' | 'follow_up'; }
export interface SellerLink { id: string; plan_id: string; status: 'active' | 'revoked'; expires_at: string | null; created_at: string; }
export interface LaunchNotice { id: string; property_id: string | null; plan_id: string | null; task_id: string | null; kind: string; title: string; detail: string | null; status: 'new' | 'read' | 'handled' | 'dismissed'; created_at: string; }

function createOpaqueToken(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (byte) => byte.toString(16).padStart(2, '0')).join('');
}
async function tokenHash(value: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value));
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
}

export const launchPlanService = {
  async listContacts(): Promise<SellerContact[]> {
    const { data, error } = await supabase.from('contacts').select('*').in('role', ['seller', 'both']).order('created_at', { ascending: false });
    if (error) throw new Error(`Could not load seller contacts: ${error.message}`);
    return (data ?? []) as SellerContact[];
  },
  async createContact(agentId: string, name: string, email?: string): Promise<SellerContact> {
    const { data, error } = await supabase.from('contacts').insert({ agent_id: agentId, name: name.trim(), email: email?.trim() || null, role: 'seller' }).select().single();
    if (error) throw new Error(`Could not create seller contact: ${error.message}`);
    return data as SellerContact;
  },
  async getOrCreatePlan(agentId: string, propertyId: string): Promise<HomeLaunchPlan> {
    const { data: existing, error: existingError } = await supabase.from('home_launch_plans').select('*').eq('property_id', propertyId).maybeSingle();
    if (existingError) throw new Error(`Could not load Home Launch Plan: ${existingError.message}`);
    if (existing) return existing as HomeLaunchPlan;
    const { data, error } = await supabase.from('home_launch_plans').insert({ agent_id: agentId, property_id: propertyId }).select().single();
    if (error) throw new Error(`Could not create Home Launch Plan: ${error.message}`);
    return data as HomeLaunchPlan;
  },
  async generateDraft(propertyId: string): Promise<Array<Pick<HomeLaunchTask, 'category' | 'title' | 'why_it_matters' | 'mandatory' | 'requires_upload' | 'requires_review'>>> {
    const { data, error } = await supabase.functions.invoke('generate-launch-plan', { body: { propertyId } });
    if (error) throw new Error(error.message || 'Could not create the Home Launch draft.');
    const tasks = (data as { tasks?: unknown })?.tasks;
    if (!Array.isArray(tasks)) throw new Error('AI returned an invalid Home Launch draft.');
    return tasks.map((task) => ({ ...(task as Pick<HomeLaunchTask, 'category' | 'title' | 'why_it_matters' | 'mandatory' | 'requires_upload'>), requires_review: true }));
  },
  async updatePlan(planId: string, updates: Partial<Pick<HomeLaunchPlan, 'seller_contact_id' | 'agent_intro' | 'launch_target_date' | 'status'>>): Promise<void> {
    const { error } = await supabase.from('home_launch_plans').update({ ...updates, updated_at: new Date().toISOString() }).eq('id', planId);
    if (error) throw new Error(`Could not save Home Launch Plan: ${error.message}`);
  },
  async listTasks(planId: string): Promise<HomeLaunchTask[]> {
    const { data, error } = await supabase.from('home_launch_tasks').select('*').eq('plan_id', planId).order('display_order');
    if (error) throw new Error(`Could not load checklist: ${error.message}`);
    return (data ?? []) as HomeLaunchTask[];
  },
  async saveTasks(agentId: string, planId: string, tasks: Array<Partial<HomeLaunchTask> & Pick<HomeLaunchTask, 'title' | 'category'>>): Promise<HomeLaunchTask[]> {
    const payload = tasks.map((task, display_order) => ({ id: task.id, agent_id: agentId, plan_id: planId, category: task.category, title: task.title.trim(), why_it_matters: task.why_it_matters?.trim() || null, mandatory: Boolean(task.mandatory), requires_upload: Boolean(task.requires_upload), requires_review: task.requires_review !== false, due_date: task.due_date || null, display_order }));
    const { error: clearError } = await supabase.from('home_launch_tasks').delete().eq('plan_id', planId);
    if (clearError) throw new Error(`Could not update checklist: ${clearError.message}`);
    if (payload.length === 0) return [];
    const { data, error } = await supabase.from('home_launch_tasks').insert(payload).select();
    if (error) throw new Error(`Could not save checklist: ${error.message}`);
    return (data ?? []) as HomeLaunchTask[];
  },
  async listNotices(propertyId: string): Promise<LaunchNotice[]> {
    const { data, error } = await supabase.from('notices').select('*').eq('property_id', propertyId).order('created_at', { ascending: false });
    if (error) throw new Error(`Could not load seller notices: ${error.message}`);
    return (data ?? []) as LaunchNotice[];
  },
  async setTaskReview(taskId: string, review: 'approved' | 'follow_up'): Promise<void> {
    const { error } = await supabase.from('home_launch_tasks').update({ agent_review_status: review, seller_status: review === 'approved' ? 'reviewed' : 'in_progress', updated_at: new Date().toISOString() }).eq('id', taskId);
    if (error) throw new Error(`Could not review checklist task: ${error.message}`);
  },
  async createSellerLink(agentId: string, planId: string): Promise<{ link: SellerLink; rawToken: string }> {
    const rawToken = createOpaqueToken();
    const { data, error } = await supabase.from('seller_links').insert({ agent_id: agentId, plan_id: planId, token_hash: await tokenHash(rawToken) }).select().single();
    if (error) throw new Error(`Could not create private Seller Link: ${error.message}`);
    await this.updatePlan(planId, { status: 'shared' });
    return { link: data as SellerLink, rawToken };
  },
  async revokeSellerLink(id: string): Promise<void> {
    const { error } = await supabase.from('seller_links').update({ status: 'revoked', updated_at: new Date().toISOString() }).eq('id', id);
    if (error) throw new Error(`Could not revoke Seller Link: ${error.message}`);
  },
};

export async function sellerLinkRequest<T>(body: Record<string, unknown>): Promise<T> {
  const response = await fetch(`${supabaseUrl}/functions/v1/seller-link`, { method: 'POST', headers: { 'Content-Type': 'application/json', apikey: supabaseAnonKey }, body: JSON.stringify(body) });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error((data as { error?: string }).error ?? 'This private link is unavailable.');
  return data as T;
}

// ─── V86 buyer workflow ───────────────────────────────────────────────────────
export interface BuyerSearch { id: string; agent_id: string; buyer_contact_id: string | null; label: string; status: 'draft' | 'waiting_preferences' | 'preferences_received' | 'source_review' | 'shortlist_shared' | 'tour_requests' | 'complete'; preferences_data: Record<string, unknown>; agent_note: string | null; created_at: string; updated_at: string; }
export interface BuyerLink { id: string; buyer_search_id: string; kind: 'preferences' | 'shortlist'; status: 'active' | 'revoked'; expires_at: string | null; created_at: string; }
export interface BuyerHome { id: string; buyer_search_id: string; title: string; listing_url: string; image_url: string | null; summary: string | null; agent_reason: string | null; display_order: number; status: 'draft' | 'sent' | 'tour_requested' | 'not_interested' | 'tour_booked'; }
export interface BuyerAvailabilitySlot { id: string; buyer_search_id: string; starts_at: string; ends_at: string; status: 'available' | 'held' | 'booked' | 'cancelled'; }

export const buyerService = {
  async createSearch(agentId: string, label: string, buyerName?: string, buyerEmail?: string): Promise<BuyerSearch> {
    let buyerContactId: string | null = null;
    if (buyerName?.trim()) {
      const { data, error } = await supabase.from('contacts').insert({ agent_id: agentId, name: buyerName.trim(), email: buyerEmail?.trim() || null, role: 'buyer' }).select().single();
      if (error) throw new Error(`Could not add buyer: ${error.message}`);
      buyerContactId = data.id;
    }
    const { data, error } = await supabase.from('buyer_searches').insert({ agent_id: agentId, buyer_contact_id: buyerContactId, label: label.trim() || 'New buyer search', status: 'draft' }).select().single();
    if (error) throw new Error(`Could not create buyer search: ${error.message}`);
    return data as BuyerSearch;
  },
  async listSearches(): Promise<BuyerSearch[]> { const { data, error } = await supabase.from('buyer_searches').select('*').order('updated_at', { ascending: false }); if (error) throw new Error(`Could not load buyer searches: ${error.message}`); return (data ?? []) as BuyerSearch[]; },
  async updateSearch(id: string, updates: Partial<Pick<BuyerSearch, 'label' | 'status' | 'preferences_data' | 'agent_note' | 'buyer_contact_id'>>): Promise<void> { const { error } = await supabase.from('buyer_searches').update({ ...updates, updated_at: new Date().toISOString() }).eq('id', id); if (error) throw new Error(`Could not save buyer search: ${error.message}`); },
  async listHomes(searchId: string): Promise<BuyerHome[]> { const { data, error } = await supabase.from('buyer_homes').select('*').eq('buyer_search_id', searchId).order('display_order'); if (error) throw new Error(`Could not load homes: ${error.message}`); return (data ?? []) as BuyerHome[]; },
  async saveHomes(agentId: string, searchId: string, homes: Array<Partial<BuyerHome> & Pick<BuyerHome, 'title' | 'listing_url'>>): Promise<BuyerHome[]> {
    const { error: removeError } = await supabase.from('buyer_homes').delete().eq('buyer_search_id', searchId); if (removeError) throw new Error(`Could not update homes: ${removeError.message}`);
    if (!homes.length) return [];
    const payload = homes.slice(0, 5).map((home, display_order) => ({ agent_id: agentId, buyer_search_id: searchId, title: home.title.trim(), listing_url: home.listing_url.trim(), image_url: home.image_url || null, summary: home.summary || null, agent_reason: home.agent_reason || null, display_order, status: 'draft' }));
    const { data, error } = await supabase.from('buyer_homes').insert(payload).select(); if (error) throw new Error(`Could not save homes: ${error.message}`); return (data ?? []) as BuyerHome[];
  },
  async saveSlots(agentId: string, searchId: string, starts: string[]): Promise<BuyerAvailabilitySlot[]> { const { error: removeError } = await supabase.from('buyer_availability_slots').delete().eq('buyer_search_id', searchId); if (removeError) throw new Error(`Could not update availability: ${removeError.message}`); const payload = starts.slice(0, 15).map((start) => ({ agent_id: agentId, buyer_search_id: searchId, starts_at: new Date(start).toISOString(), ends_at: new Date(new Date(start).getTime() + 60 * 60 * 1000).toISOString() })); if (!payload.length) return []; const { data, error } = await supabase.from('buyer_availability_slots').insert(payload).select(); if (error) throw new Error(`Could not save availability: ${error.message}`); return (data ?? []) as BuyerAvailabilitySlot[]; },
  async createLink(agentId: string, searchId: string, kind: BuyerLink['kind']): Promise<{ link: BuyerLink; rawToken: string }> { const rawToken = createOpaqueToken(); const { data, error } = await supabase.from('buyer_links').insert({ agent_id: agentId, buyer_search_id: searchId, kind, token_hash: await tokenHash(rawToken) }).select().single(); if (error) throw new Error(`Could not create private Buyer Link: ${error.message}`); await this.updateSearch(searchId, { status: kind === 'preferences' ? 'waiting_preferences' : 'shortlist_shared' }); if (kind === 'shortlist') await supabase.from('buyer_homes').update({ status: 'sent', updated_at: new Date().toISOString() }).eq('buyer_search_id', searchId).eq('status', 'draft'); return { link: data as BuyerLink, rawToken }; },
  async reviewSources(searchId: string): Promise<{ homes: Array<{ title: string; url: string; match_reason: string; source_title: string }> }> { const { data, error } = await supabase.functions.invoke('review-buyer-sources', { body: { buyerSearchId: searchId } }); if (error) throw new Error(error.message || 'Could not review current sources.'); return data as { homes: Array<{ title: string; url: string; match_reason: string; source_title: string }> }; },
};

export async function buyerLinkRequest<T>(body: Record<string, unknown>): Promise<T> { const response = await fetch(`${supabaseUrl}/functions/v1/buyer-link`, { method: 'POST', headers: { 'Content-Type': 'application/json', apikey: supabaseAnonKey }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error((data as { error?: string }).error ?? 'This private link is unavailable.'); return data as T; }
export async function buyerPreferenceTranscribe<T>(body: { token: string; audioBase64: string; mimeType: string }): Promise<T> { const response = await fetch(`${supabaseUrl}/functions/v1/transcribe-buyer-preferences`, { method: 'POST', headers: { 'Content-Type': 'application/json', apikey: supabaseAnonKey }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error((data as { error?: string }).error ?? 'Could not read that recording.'); return data as T; }
export async function agentBuyerBriefTranscribe<T>(body: { buyerSearchId: string; audioBase64: string; mimeType: string }): Promise<T> { const { data, error } = await supabase.functions.invoke('transcribe-agent-buyer-brief', { body }); if (error) throw new Error(error.message || 'Could not prepare the buyer brief.'); return data as T; }
