import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const root = new URL('..', import.meta.url);
const read = (path) => readFileSync(new URL(path, root), 'utf8');
const migration = read('supabase/migrations/20260826000000_add_buyer_workflow.sql');
const home = read('src/components/home/HomeScreen.tsx');
const workspace = read('src/components/buyer/BuyerWorkspace.tsx');
const portal = read('src/components/buyer/BuyerPortal.tsx');
const app = read('src/App.tsx');
const buyerLink = read('supabase/functions/buyer-link/index.ts');
const sourceReview = read('supabase/functions/review-buyer-sources/index.ts');
const transcribe = read('supabase/functions/transcribe-buyer-preferences/index.ts');

assert.match(home, /What are you doing today\?/);
assert.match(home, /Find a house for my buyer/);
assert.match(app, /BuyerWorkspace/);
assert.match(app, /buyerToken/);
assert.match(app, /BuyerPortal token/);
assert.match(migration, /CREATE TABLE IF NOT EXISTS buyer_searches/);
assert.match(migration, /CREATE TABLE IF NOT EXISTS buyer_links/);
assert.match(migration, /CREATE TABLE IF NOT EXISTS buyer_homes/);
assert.match(migration, /CREATE TABLE IF NOT EXISTS buyer_availability_slots/);
assert.match(migration, /CREATE TABLE IF NOT EXISTS tour_requests/);
assert.match(migration, /ENABLE ROW LEVEL SECURITY/);
assert.match(workspace, /Create preferences link/);
assert.match(workspace, /Review selected sources/);
assert.match(workspace, /Create magical Buyer Link/);
assert.match(portal, /Record preferences/);
assert.match(portal, /Send to agent/);
assert.match(portal, /I want to tour/);
assert.match(portal, /Request this tour/);
assert.match(buyerLink, /token_hash/);
assert.match(buyerLink, /submit_preferences/);
assert.match(buyerLink, /request_tour/);
assert.match(buyerLink, /tour_requests/);
assert.match(transcribe, /Preserve uncertainty/);
assert.match(sourceReview, /never persisted/);
assert.match(sourceReview, /groundingMetadata/);
assert.match(sourceReview, /allowedHosts/);
console.log('V86 buyer-workflow contract checks passed.');
